import archived from "./archived.json" with { type: "json" };
import pinned from "./pinned.json" with { type: "json" };
import community from "./11ty-community.json" with { type: "json" };
import emeritus from "./11ty-emeritus.json" with { type: "json" };
import starters from "./11ty-starters.json" with { type: "json" };

/**
 * Starter projects and templates.
 *
 * Mostly imported from 11ty/docs, which is the canonical list — its `demo`
 * field is the deployed site, and entries it marks `excludedFromLeaderboards`
 * are honoured rather than second-guessed. `EXTRA_STARTERS` is for anything
 * spotted in the community list that upstream does not carry.
 *
 * The union also filters the community category: a starter that appears in both
 * lists belongs here, and deleting it from the generated community file would
 * only last until the next import. Excluding it at this level keeps that file
 * exactly as upstream sends it.
 */
const EXTRA_STARTERS = [
	"https://11skeleton.vercel.app/",
	"https://eleventy-test-bed-dollplayer2501.netlify.app/",
	"https://eleventy-step.netlify.app/",
	"https://multilingual.lea-tortay.com/",
	"https://yetty.netlify.app/",
];
const STARTERS = [...new Set([...starters.urls, ...EXTRA_STARTERS])];

/**
 * Sites that used to be built with Eleventy or Build Awesome.
 *
 * `config/11ty-emeritus.json` holds the bulk of them, recovered from the
 * community repo's git history. `EXTRA_EMERITUS` is the place to add one by
 * hand — a site you know has moved on but whose page says nothing either way,
 * so the generator rule cannot see it.
 *
 * Nothing needs adding here for the ordinary case: a site measured as a
 * different generator is moved automatically at report time. This is only for
 * what measurement cannot detect.
 *
 * Like STARTERS, the union also filters the community category, so a URL listed
 * here leaves Built Awesome rather than appearing in both.
 *
 * Normalized form: https, trailing slash on a bare origin, none on a path.
 */
const EXTRA_EMERITUS = ["https://annotator.incubator.apache.org/"];

/**
 * Community sites added by hand.
 *
 * `config/11ty-community.json` is generated by scripts/import-11ty-community.mjs
 * and rewritten whole on every import, so a URL added there lasts until the next
 * run. This is where one goes to stay — for sites that belong on the list but
 * are not on it upstream, or were dropped from it and should not have been.
 *
 * Anything here almost certainly wants pinning too: the category moves a site
 * out when its page reports a generator other than Eleventy, and a site being
 * re-added by hand is usually one that reports something unusual. See
 * `pinned` below.
 */
const EXTRA_COMMUNITY = [
	"https://cassettenest.com/",
	"https://open-wc.org/",
	"https://www.ryzokuken.dev/",
];
const EMERITUS = [...new Set([...emeritus.urls, ...EXTRA_EMERITUS])];

/**
 * The list of sites to measure.
 *
 * Add or remove entries here — everything else (results, history, the static
 * site) keys off of the `url`, so renaming a site keeps its history but
 * changing a URL starts a fresh history for that URL.
 */
/**
 * Sites taken out of circulation.
 *
 * Archiving is the middle option. Deleting a URL loses its measurements and
 * leaves an orphaned history behind; leaving it in place keeps a dead site in
 * the rankings and keeps sending traffic to it. An archived site keeps its
 * record, stops being measured, and appears only as plain text — no row, no
 * link, no page.
 *
 * Applies across every category at once, so a URL listed in two of them does
 * not need archiving twice.
 */
const ARCHIVED = archived.urls;

/**
 * Sites held where this config puts them.
 *
 * Categories normally reclassify themselves: `requireGenerator` moves a site out
 * of Built Awesome when its page reports something else, and `rejectGenerator`
 * moves it back out of Emeritus when it reports Eleventy again. That is right
 * almost always, and it re-applies on every build — so a category change made by
 * hand does not survive the next report unless the detection agrees with it.
 *
 * This is the exception list for when detection is reading the page correctly
 * and still getting the answer wrong: a stale generator tag left in a template,
 * a proxy or platform stamping its own, a site built with one thing and
 * reporting another. A URL here keeps whatever categories it is listed in.
 *
 * Not a way to disagree with a correct detection. A site that really has moved
 * to Astro belongs in Emeritus, and pinning it there would make this list a
 * quiet second source of truth about what built the web.
 */
const PINNED = pinned.urls;

/**
 * The two cadences, and the one politeness setting, that repeat across
 * categories.
 *
 * Spread into a group rather than retyped: these are the same decision applied
 * to several lists, and seven copies of the same four lines is how one of them
 * ends up a hundred hours out of step with the rest for no reason anybody can
 * reconstruct.
 */

/** Hand-maintained handfuls: measured daily, stale after two days. */
const DAILY = { freshnessHours: 24, staleAfterHours: 48 };

/** The big imported lists: weekly, stale after a fortnight. */
const WEEKLY = { freshnessHours: 24 * 7, staleAfterHours: 24 * 7 * 2 };

/**
 * Other people's sites, mostly on modest hosting, measured at a deliberate
 * pace. Measurement is already sequential — one Chrome, one run at a time — so
 * nothing is ever requested concurrently; this governs the pace on top of that.
 *
 * At 3s between sites plus ~15s to measure one, each person's server sees a
 * handful of page loads once per cycle: no more than a single visitor would
 * generate. The host cooldown is belt and braces, for two entries that turn out
 * to share a domain.
 */
const POLITE = { rateLimit: { delayMs: 3000, hostCooldownMs: 60000 } };

/*
 * The four tooling categories' site lists, named so the combined category below
 * can reference them rather than repeat them. Each still has its own page; the
 * union is an additional view, not a replacement.
 */
const SSG_SITES = [
				{ name: "Eleventy", url: "https://www.11ty.dev/" },
				{ name: "Astro", url: "https://astro.build/" },
				{ name: "Svelte", url: "https://svelte.dev/" },
				{ name: "Hugo", url: "https://gohugo.io/" },
				{ name: "Jekyll", url: "https://jekyllrb.com/" },
				{ name: "VuePress", url: "https://vuepress.vuejs.org/" },
				{ name: "VitePress", url: "https://vitepress.dev/" },
				{ name: "Docusaurus", url: "https://docusaurus.io/" },
				{ name: "Gridsome", url: "https://gridsome.org/" },
				{ name: "Next.js", url: "https://nextjs.org/" },
				{ name: "Gatsby", url: "https://www.gatsbyjs.com/" },
				{ name: "Lume", url: "https://lume.land/" },
				{ name: "Hexo", url: "https://hexo.io/" },
				{ name: "Remix", url: "https://remix.run/" },
				{ name: "Nuxt", url: "https://nuxt.com/" },

				// Added here rather than in the imported order above: the upstream
				// list predates it.
				{ name: "Zola", url: "https://www.getzola.org/" },
			];

const TEST_RUNNER_SITES = [
				{ name: "QUnit", url: "https://qunitjs.com/" },
				{ name: "webhint", url: "https://webhint.io/" },
				{ name: "Mocha", url: "https://mochajs.org/" },
				{ name: "ESLint", url: "https://eslint.org/" },
				{ name: "Istanbul", url: "https://istanbul.js.org/" },
				{ name: "gulp", url: "https://gulpjs.com/" },
				{ name: "Grunt", url: "https://gruntjs.com/" },
				{ name: "WebdriverIO", url: "https://webdriver.io/" },
				{ name: "Intern", url: "https://theintern.io/" },

				// The three that took over after this list was written: on npm,
				// Vitest and Playwright run at roughly 97M and 86M a week.
				{ name: "Vitest", url: "https://vitest.dev/" },
				{ name: "Playwright", url: "https://playwright.dev/" },
				{ name: "Puppeteer", url: "https://pptr.dev/" },
			];

const PACKAGE_MANAGER_SITES = [
				{ name: "npm", url: "https://www.npmjs.com/" },
				{ name: "Yarn", url: "https://yarnpkg.com/" },
				{ name: "JSR", url: "https://jsr.io/" },
				{ name: "npmx", url: "https://npmx.dev/" },
				{ name: "PyPI", url: "https://pypi.org/" },
				{ name: "crates.io", url: "https://crates.io/" },
				{ name: "Packagist", url: "https://packagist.org/" },
				{ name: "RubyGems", url: "https://rubygems.org/" },
				{ name: "Maven Central", url: "https://central.sonatype.com/" },
				{ name: "NuGet", url: "https://www.nuget.org/" },
				{ name: "pkg.go.dev", url: "https://pkg.go.dev/" },
				{ name: "pub.dev", url: "https://pub.dev/" },
				{ name: "Hex", url: "https://hex.pm/" },
				{ name: "Homebrew", url: "https://brew.sh/" },

				/*
				 * Documentation sites, not package browsers (left out for now)
				 */
				// { name: "pnpm", url: "https://pnpm.io/" },
				// { name: "vlt", url: "https://www.vlt.io/" },
				// { name: "jspm", url: "https://jspm.org/" },
				// { name: "uv", url: "https://docs.astral.sh/uv/" },
				// { name: "Chocolatey", url: "https://chocolatey.org/" },
			];

const HOST_SITES = [
				{ name: "Netlify", url: "https://www.netlify.com/", groups: ["11ty-emeritus"] },
				{ name: "Vercel", url: "https://vercel.com/" },
				{ name: "Cloudflare", url: "https://www.cloudflare.com/" },
				{ name: "Cloudflare Pages", url: "https://pages.cloudflare.com/" },
				{ name: "GitHub Pages", url: "https://pages.github.com/" },
				{ name: "GitLab Pages", url: "https://docs.gitlab.com/user/project/pages/" },
				{ name: "Fly.io", url: "https://fly.io/" },
				{ name: "Render", url: "https://render.com/" },
				{ name: "Railway", url: "https://railway.com/" },
				{ name: "Deno Deploy", url: "https://deno.com/deploy" },
				{ name: "Fastly", url: "https://www.fastly.com/" },
				{ name: "Bunny", url: "https://bunny.net/" },
				{ name: "DigitalOcean", url: "https://www.digitalocean.com/" },
				{ name: "Heroku", url: "https://www.heroku.com/" },
				{ name: "Surge", url: "https://surge.sh/" },
				{ name: "Neocities", url: "https://neocities.org/" },
				{ name: "Codeberg Pages", url: "https://codeberg.page/" },

				// Product pages rather than roots: these three are hosting products
				// inside far larger sites, and the company's front door would be
				// measuring something else entirely.
				{ name: "Firebase Hosting", url: "https://firebase.google.com/products/hosting" },
				{ name: "AWS Amplify", url: "https://aws.amazon.com/amplify/" },
				{ name: "Azure Static Web Apps", url: "https://azure.microsoft.com/en-us/products/app-service/static" },
			];

/*
 * UI frameworks, which none of the four lists above is the right home for: not
 * generators, not runners, not registries, not hosts. They exist so Developer
 * Tooling can carry them — the category is about the people who build the tools,
 * and these are the tools most of the sites in it are built with.
 */
const FRAMEWORK_SITES = [
	{ name: "React", url: "https://react.dev/" },
	{ name: "Vue", url: "https://vuejs.org/" },
	{ name: "Angular", url: "https://angular.dev/" },
	{ name: "Preact", url: "https://preactjs.com/" },
	{ name: "Lit", url: "https://lit.dev/" },
	// In both this list and SSG_SITES, deliberately: svelte.dev documents Svelte
	// and SvelteKit together, so the one page is a framework's home and a site
	// generator's. loadConfig dedupes by URL, so the site is measured once and
	// simply belongs to both categories.
	{ name: "Svelte", url: "https://svelte.dev/" },
	{ name: "SolidJS", url: "https://www.solidjs.com/" },
	{ name: "Qwik", url: "https://qwik.dev/" },

	{ name: "React Router", url: "https://reactrouter.com/" },
	{ name: "TanStack", url: "https://tanstack.com/" },

	// The no-build-step position, which is the argument this project's readers
	// are most likely to be having. Small by download count and loud by
	// influence — worth measuring for what their own pages do.
	{ name: "Alpine.js", url: "https://alpinejs.dev/" },
	{ name: "htmx", url: "https://htmx.org/" },

	// The older guard. Both are past the point where anyone surveys them, and
	// both are still on a great many more pages than that suggests.
	{ name: "Ember", url: "https://emberjs.com/" },
	{ name: "jQuery", url: "https://jquery.com/" },
];

/*
 * Package managers whose home page is documentation rather than a registry.
 *
 * They are commented out of PACKAGE_MANAGER_SITES on purpose — that category is
 * package *browsers*, and a docs site beside a search UI compares two different
 * jobs. Here the question is only whether the tool has one, so they belong.
 */
const PACKAGE_TOOL_SITES = [
	{ name: "pnpm", url: "https://pnpm.io/" },
	// vlt.sh redirects to vlt.io; pinned to the destination.
	{ name: "vlt", url: "https://www.vlt.io/" },
	{ name: "jspm", url: "https://jspm.org/" },
];

/*
 * What compiles and bundles the rest. Not frameworks and not test runners, but
 * the same kind of thing as both: a tool whose home page is its shop window.
 */
const BUILD_TOOL_SITES = [
	{ name: "TypeScript", url: "https://www.typescriptlang.org/" },
	{ name: "Vite", url: "https://vite.dev/" },
	{ name: "esbuild", url: "https://esbuild.github.io/" },
	{ name: "webpack", url: "https://webpack.js.org/" },
];

export default {
	// Read by lib/config.js, which marks the matching sites as it flattens the
	// groups — one place rather than a filter on each category's list.
	archived: ARCHIVED,

	// Exempt from the generator rules, same mechanism. A site entry can also
	// carry `pinGroup: true` directly, for the hand-written categories; this list
	// is for the ones whose entries come from a generated file.
	pinned: PINNED,

	// Lighthouse runs per URL per measurement. The median run is kept.
	// 3 is a decent tradeoff between noise and wall-clock time.
	runs: 3,

	// Whether to keep Lighthouse's loading filmstrip: "filmstrip" or "none",
	// overridable per category and per site.
	//
	// These files are committed, since measure and publish are separate
	// workflows on separate checkouts and the repository is the only channel
	// between them. A deduplicated strip measured 19–84 KB per site, so at this
	// corpus size expect roughly 75 MB in the tree, rewritten weekly as sites
	// are re-measured. Set a category to "none" to keep it out.
	screenshots: "filmstrip",

	// "mobile" (throttled, Moto G Power emulation) or "desktop"
	formFactor: "mobile",

	// Skip a URL if it was already measured within this many hours.
	// Set to 0 to always re-measure.
	freshnessHours: 24 * 7,

	// How many sites a single `speedlify measure` will do before stopping.
	// Measurement is a rolling process: each run spends this budget on whichever
	// sites are most out of date, so you size this to the time you're willing to
	// give one invocation, not to the length of the site list.
	//
	// With ~2,300 sites this must not be null — an unbounded run would try the
	// whole list and take about eleven hours. At 40, a run is roughly 12 minutes,
	// and four shards every two hours cover every site in a bit over a day.
	batchSize: 40,

	// Data older than this is shown as stale in the report and in `speedlify list`.
	staleAfterHours: 24 * 7 * 2,

	// How many recent points the report charts. Since the build reads the compact
	// series.json rather than the raw records, this is a readability choice
	// rather than a performance guard — set it to null to chart everything.
	historyLimit: 120,

	// How long a site whose last attempt errored waits before being tried again.
	// An error is not data, so a failure never earns the site a freshness window
	// — this is the only thing holding it back. 0 means the very next run.
	//
	// Overridable per category, same as freshnessHours: a handful of framework
	// home pages can retry immediately while thousands of personal sites wait.
	retryErrorsAfterHours: 6,

	// Escalate that wait exponentially with each consecutive failure — 1h, 2, 4,
	// 8, 16, capped at 24 — so a URL that has been dead for a week stops
	// consuming a slot in every batch. The two compose: the wait is whichever of
	// the curve and retryErrorsAfterHours is longer.
	failureBackoff: true,

	// A redirect must lead to the same destination on this many consecutive
	// successful measurements before it is treated as a real site move. Guards
	// against A/B tests, geo splits and maintenance pages, which all look like
	// redirects for a run or two.
	redirectConfirmations: 3,

	// Any category can be switched off with `enabled: false`. It stops being
	// measured and stops appearing on the site, but nothing is deleted — its
	// stored history stays put and comes straight back when it is re-enabled.
	//
	// A site listed in a disabled category and nowhere else drops out of the
	// corpus entirely, so its history will read as orphaned meanwhile.
	/*
	 * Addresses that used to mean something, and where they go now.
	 *
	 * Two kinds, both for the same reason: a URL people linked to and search
	 * engines remember should not become a 404.
	 *
	 * The bare paths are the original Speedlify's scheme, where a category was
	 * served from the root — `/ssg/` rather than `/group/ssg/`. This instance
	 * replaced that site at the same domain, so those links are still out there.
	 *
	 * Destinations are checked at report time against the categories and sites
	 * that actually exist — see lib/report.js — so an entry pointing at something
	 * since renamed is dropped rather than published as a link to nowhere.
	 */
	redirects: {
		"/ssg/": "/group/ssg/",
		"/test-runners/": "/group/test-runners/",
		"/zachleat.com/": "/group/zachleat/",
		"/sample/": "/site/www-speedlify-dev/",

	},

	groups: {
		/*
		 * Site Generators, Test Runners, Package Managers and Web Hosts, in one
		 * place.
		 *
		 * An additional view rather than a replacement: every site here is still
		 * on its own category page, and still ranked there against its own kind.
		 * What this adds is the comparison those pages cannot make — a generator's
		 * site against the host it deploys to against the registry it publishes
		 * to, all built by people who do this for a living.
		 *
		 * Listed first, which makes it every member's primary category: `groups`
		 * is walked in order and the first match wins. So a hosting company reads
		 * "Developer Tooling" on the leaderboard, with "Web Hosts" as the second
		 * chip — the general label first, the specific one after it.
		 *
		 * The sites are the same objects the four use, so a URL added to one of
		 * them appears here on the next build without a second edit.
		 */
		"dev-tooling": {
			showOnHomePageCategoryList: true,
			name: "Developer Tooling",
			enabled: true,
			description:
				"Site generators, test runners, package managers and web hosts together. The people who build the tools, measured on the sites they use to sell them.",
			...DAILY,
			sites: [
				...SSG_SITES,
				...TEST_RUNNER_SITES,
				...PACKAGE_MANAGER_SITES,
				...HOST_SITES,
				...FRAMEWORK_SITES,
				...BUILD_TOOL_SITES,
				...PACKAGE_TOOL_SITES,

				// This instance, in its own leaderboard. Not in any of the lists
				// above because there is no list of one — and measuring the thing
				// that does the measuring is the least it can do.
				{ name: "Speedlify", url: "https://www.speedlify.dev/" },
			],
		},

		ssg: {
			showOnHomePageCategoryList: true,
			name: "Site Generators",
			enabled: true,
			description: "Home pages for popular site generators and frameworks.",
			...DAILY,
			// The list from https://www.speedlify.dev/ssg/, in its order.
			sites: SSG_SITES,
		},

		frameworks: {
			showOnHomePageCategoryList: true,
			name: "Frameworks and Libraries",
			enabled: true,
			description:
				"What pages are built with, measured on the pages that sell them. A framework's own site is the one page its authors control completely — and the one place the tradeoffs they chose are on display rather than described.",
			...DAILY,

			sites: FRAMEWORK_SITES,
		},

		"test-runners": {
			name: "Test Runners",
			enabled: true,
			description: "Home pages for JavaScript test runners and linters.",
			...DAILY,


			sites: TEST_RUNNER_SITES,
		},

		"package-managers": {
			name: "Package Managers",
			enabled: true,
			description:
				"Package browsers: the searchable front ends to a package registry. Every one of these has a similar job \u2014 a search box over a package index.",
			...DAILY,
			sites: PACKAGE_MANAGER_SITES,
		},

		hosts: {
			showOnHomePageCategoryList: true,
			name: "Web Hosts",
			enabled: true,
			description:
				"Home pages of the hosting and deploy platforms this project detects in the Host column.",
			...DAILY,
			sites: HOST_SITES,
		},

		builders: {
			showOnHomePageCategoryList: true,
			name: "Website Builders",
			enabled: true,
			description:
				"Hosted tools that build and serve a site for you. The counterweight to every other category here: these pages are what a site looks like when the person making it never sees the output.",
			...DAILY,
			sites: [
				{ name: "WordPress.com", url: "https://wordpress.com/" },
				{ name: "Shopify", url: "https://www.shopify.com/" },
				{ name: "Wix", url: "https://www.wix.com/" },
				{ name: "Squarespace", url: "https://www.squarespace.com/" },
				{ name: "Tilda", url: "https://tilda.cc/" },
				{ name: "Webflow", url: "https://webflow.com/" },
				{ name: "Duda", url: "https://www.duda.co/" },
				{ name: "Framer", url: "https://www.framer.com/" },
				{ name: "Nordcraft", url: "https://nordcraft.com/" },
			],
		},

		zachleat: {
			name: "zachleat.com",
			enabled: true,
			description: "Pages from zachleat.com.",
			...WEEKLY,
			...POLITE,
			sites: [
				{ url: "https://www.zachleat.com/" },
				{ url: "https://www.zachleat.com/about/" },
				{ url: "https://www.zachleat.com/resume/" },
				{ url: "https://www.zachleat.com/twitter/" },
				{ url: "https://www.zachleat.com/web/" },
				{ url: "https://www.zachleat.com/web/eleventy/" },
				{ url: "https://www.zachleat.com/web/fonts/" },
				{ url: "https://www.zachleat.com/web/speedlify/" },
				{ url: "https://www.zachleat.com/web/lighthouse-in-footer/" },
				{ url: "https://www.zachleat.com/web/comprehensive-webfonts/" },
				{ url: "https://www.zachleat.com/web/google-fonts-display/" },
			],
		},

		"11ty-community": {
			showOnHomePageCategoryList: true,
			name: "Built Awesome",
			enabled: true,
			description:
				'Community-submitted sites from the <a href="https://github.com/11ty/11ty-community">11ty/11ty-community</a> repository.',

			// Where someone adds a site to this category, and what that act is
			// called. The list is imported from an issue template upstream, so the
			// answer is a form rather than a pull request against this repository —
			// which is not something a reader could guess from the description.
			//
			// Categories without this get no call to action: for the hand-written
			// ones the answer really is "open a PR", and a button saying so is a
			// worse version of the repository link in the footer.
			submitUrl: "https://github.com/11ty/11ty-community/issues/new?template=built-with-eleventy.yml",
			submitLabel: "Add your site",

			...POLITE,
			...WEEKLY,
			// for storage reasons
			screenshots: "none",

			// The list is a record of what was submitted, not of what is true now.
			// A site measured as something other than Eleventy has moved on, so it
			// moves to the category below rather than inflating this one.
			//
			// Matched on the detected generator's id, and only when there is one:
			// no generator tag is the normal case for a static site and proves
			// nothing either way, so those stay put. Both names for the same
			// project qualify — "Build Awesome" is Eleventy's newer branding and
			// reports under its own id, so it has to be listed explicitly.
			requireGenerator: ["eleventy", "build-awesome"],
			emeritusGroup: "11ty-emeritus",

			// Most static sites emit no generator tag at all, so a blank is the
			// common case here rather than a suspicious one. Being on this list is
			// itself a claim about what built the site — shown faded, because it is
			// what someone submitted rather than what we measured.
			presumedGenerator: "build-awesome",

			// Generated by scripts/import-11ty-community.mjs — re-run it to refresh.
			//
			// Two lists are filtered out rather than deleted from the generated
			// file, which a re-import would only undo: starters, and anything
			// hand-listed as emeritus. Adding a URL to config/11ty-emeritus.json is
			// therefore the whole of moving it — it appears there and leaves here.
			//
			// The automatic path still works alongside this: a site measured as a
			// different generator is moved by requireGenerator below, no editing
			// needed. This is for the cases measurement cannot see.
			sites: [...new Set([...community.urls, ...EXTRA_COMMUNITY])]
				.filter((url) => !STARTERS.includes(url) && !EMERITUS.includes(url))
				.map((url) => ({ url })),
		},

		"11ty-starters": {
			showOnHomePageCategoryList: true,
			name: "Build Awesome Starters",
			description:
				"Starter projects and templates built with Eleventy. Measured apart from the community list because a starter is a demonstration of a stack rather than a site someone runs.",

			// A directory of data files in 11ty/docs rather than an issue form:
			// this list is imported from there, so a starter is added by adding a
			// file upstream. See EXTRA_STARTERS above for the ones we carry that
			// upstream does not.
			submitUrl: "https://github.com/11ty/docs/tree/main/src/_data/starters",
			submitLabel: "Add a starter",

			...POLITE,
			...WEEKLY,

			// for storage reasons
			screenshots: "none",

			// The ones that came from the community list were filtered out of it,
			// not missing from it. Without this they would be flagged "unlisted"
			// — told to submit something that is already submitted.
			listedIn: "11ty-community",

			// Kept out of the home page's Perfect Scores board. A starter is a
			// near-empty demonstration page, so a perfect score there is the
			// expected result rather than an achievement, and enough of them would
			// crowd out the real sites the board exists to show. They still rank
			// normally on their own category page and in the global leaderboard.
			excludeFromPerfectScores: true,

			// Same reasoning as the community list above: a starter emits no
			// generator tag any more often than a finished site does, and being on
			// this list is itself a claim about what built it. Shown faded, because
			// it is what the docs say rather than what we measured.
			//
			// No requireGenerator to go with it, unlike the community list. A
			// starter that stops being Eleventy stops being an Eleventy starter and
			// gets removed upstream; there is no "used to be a starter" category for
			// it to age into.
			presumedGenerator: "build-awesome",

			// Generated by scripts/import-11ty-starters.mjs — re-run it to refresh.

			sites: STARTERS.map((url) => ({ url })),
		},

		"11ty-emeritus": {
			name: "11ty Emeritus",

			// Not a competition. These sites left, and ranking what they scored on
			// the way out invites a reading nobody intended — that the list is a
			// wall of shame, or that the site at the top is the best of a bad lot.
			// The page still measures them; it just does not place them.
			ranked: false,

			// And no "Biggest movers" panel, for the same reason: a site that has
			// moved on is not a contestant whose form is worth remarking on.
			movers: false,

			enabled: true,
			description:
				"Sites that were previously built with Eleventy or Build Awesome but have moved away (since April 2018).",

			...POLITE,
			...WEEKLY,

			// for storage reasons
			screenshots: "none",

			// Two ways in. Sites listed here were deleted from the community repo
			// upstream — recovered from its git history, since a deletion removes
			// the URL entirely and the generator rule never gets to see it.
			//
			// The rest arrive at report time: anything still on the community list
			// that measures as a different generator is moved here automatically.
			// The category is defined by what a site *used* to be built with, so one
			// measuring as Eleventy again does not belong here — it has come back,
			// and saying otherwise would state the opposite of the truth. The
			// mirror image of requireGenerator above.
			//
			// As there, an undetected generator decides nothing: most static sites
			// emit no tag, and absence is not evidence of a return.
			rejectGenerator: ["eleventy", "build-awesome"],
			rejectGroup: "11ty-community",

			sites: EMERITUS.map((url) => ({ url })),
		},
	},
};
